<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-NCHRHGP" failures="2" tests="9" name="RerunTest" time="0.072" errors="0" timestamp="2021-05-25T17:58:01 IST">
  <testcase classname="rerunTest_method1.Test1" name="TestMethod1" time="0.009"/>
  <testcase classname="rerunTest_method1.Test1" name="TestMethod2" time="0.001"/>
  <testcase classname="rerunTest_method1.Test1" name="TestMethod3" time="0.002"/>
  <testcase classname="rerunTest_method1.Test2" name="TestMethod4" time="0.003">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at rerunTest_method1.Test2.TestMethod4(Test2.java:10)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- TestMethod4 -->
  <testcase classname="rerunTest_method1.Test2" name="TestMethod5" time="0.001"/>
  <testcase classname="rerunTest_method1.Test2" name="TestMethod6" time="0.001"/>
  <testcase classname="rerunTest_method1.Test3" name="TestMethod7" time="0.001"/>
  <testcase classname="rerunTest_method1.Test3" name="TestMethod8" time="0.0">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at rerunTest_method1.Test3.TestMethod8(Test3.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- TestMethod8 -->
  <testcase classname="rerunTest_method1.Test3" name="TestMethod9" time="0.001"/>
</testsuite> <!-- RerunTest -->
